[workspace]
members = ["sm83", "sm83/tester"]

[package]
name = "gamewaifu"
version = "0.1.0"
edition = "2021"

[dependencies]
sm83 = { version = "0.1.0", path = "sm83" }

[profile.dev]
overflow-checks = false
