[workspace]
members = [ "ppu","sm83", "sm83/tester"]

[package]
name = "gamewaifu"
version = "0.1.0"
edition = "2021"

[dependencies]
ppu = { version = "0.1.0", path = "ppu" }
sm83 = { version = "0.1.0", path = "sm83" }
raylib = "5.0.1"

[profile.dev]
overflow-checks = false
