[package]
name = "front_raylib"
version = "0.1.1"
edition = "2021"

[dependencies]
gb = { path = "../gb" }
raylib = "5.0.1"
rodio = { version = "0.19", default-features = false }
clap = { version = "4.5.7", features = ["derive"] }
gif = "0.13.1"
